### ISSUE TITLE
run swift build , error: type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by tttpeng** [necolt/Swifton-TodoApp#5]
Cloning Packages/Swifton
Cloning Packages/Stencil
/Users/tpeng/Desktop/swift-server/Swifton-TodoApp/Packages/Stencil/Package.swift:6:6: error: type of expression is ambiguous without more context
    .Package(url: "https://github.com/kylef/PathKit.git", majorVersion: 0, minor: 6),
    ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
swift-build: exit(1): ["/Library/Developer/Toolchains/swift-2.2-SNAPSHOT-2015-12-01-a.xctoolchain/usr/bin/swiftc", "--driver-mode=swift", "-I", "/Library/Developer/Toolchains/swift-2.2-SNAPSHOT-2015-12-01-a.xctoolchain/usr/lib/swift/pm", "-L", "/Library/Developer/Toolchains/swift-2.2-SNAPSHOT-2015-12-01-a.xctoolchain/usr/lib/swift/pm", "-lPackageDescription", "-target", "x86_64-apple-macosx10.10", "/Users/tpeng/Desktop/swift-server/Swifton-TodoApp/Packages/Stencil/Package.swift"]

**Comment by sauliusgrigaitis** [comment]
@tttpeng you are using too old `swift-2.2-SNAPSHOT-2015-12-01`. Please install latest [DEVELOPMENT snapshot](https://github.com/necolt/Swifton-TodoApp/blob/master/.swift-version) and try again.

**Comment by tttpeng** [comment]
Yeah, Thank you very much
