### ISSUE TITLE
Route Not Found

### ISSUE THREAD

**Issue by XiangNanLi** [necolt/Swifton-TodoApp#6]
I do not know how to exit the app.

I build the app on the first day , and run './.build/debug/Swifton-TodoApp' ,  then I input the url "0.0.0.0:8000" . Yeah , success.

when I build on the second day , success . but when I open the url , it shows 'Route Not Found"

**Comment by XiangNanLi** [comment]
I remove the Package folder , then 'swift build' . 
but it also show 'Route Not Found'.
do't know why...

**Comment by sauliusgrigaitis** [comment]
Please check README, it says `http://0.0.0.0:8000/todos`

**Comment by XiangNanLi** [comment]
...yeah. Thanks, sir.
