### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by nonameplum** [necolt/Swifton-TodoApp#7]
`$ swift build
Cloning https://github.com/necolt/Swifton.git
Resolved version: 0.0.5
Cloning https://github.com/necolt/Stencil.git
Resolved version: 0.5.2
Cloning https://github.com/kylef/PathKit.git
Resolved version: 0.6.1
Cloning https://github.com/necolt/Inquiline.git
Resolved version: 0.2.2
Cloning https://github.com/nestproject/Nest.git
Resolved version: 0.2.1
Cloning https://github.com/necolt/URITemplate.swift.git
Resolved version: 1.3.1
Cloning https://github.com/necolt/Curassow.git
Resolved version: 0.4.0
Cloning https://github.com/kylef/Commander.git
Resolved version: 0.4.1
error: NoSources(".../Swifton-TodoApp-master/Packages/PathKit-0.6.1/Tests/Fixtures")`

`$ swift --version
Apple Swift version 3.0-dev (LLVM b361b0fc05, Clang 11493b0f62, Swift fc261045a5)`

`$ swiftenv version
DEVELOPMENT-SNAPSHOT-2016-02-25-a (set by /.../Swifton-TodoApp-master/.swift-version)`

**Comment by sauliusgrigaitis** [comment]
@nonameplum thanks, it's known [issue](https://github.com/kylef/PathKit/issues/11) with latest `DEVELOPMENT-SNAPSHOT-2016-02-25-a` , please install a bit older `DEVELOPMENT-SNAPSHOT-2016-02-08-a`
